services:
  public:
    environment:
      - NODE_ENV=production
      - VITE_SERVER_PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_URI=${MONGO_DOCKER_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_TRIAL_PRICE_ID=${STRIPE_TRIAL_PRICE_ID}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
